#!/usr/bin/env bash

read -p "[?] This script will modify the files: .vim and .vimrc ...  Continue [y/n]: "  choice

if [[ $choice != "y" ]]; then
    echo
    echo "[-] Exiting... "
    exit 1
fi

if [[ ! -d $HOME/.vim ]]; then
    echo "[*] Created ~/.vim"
    mkdir ~/.vim
fi

if [[ ! -d $HOME/.vim/bundle/ ]]; then
    echo "[*] Created ~/.vim/bundle"
    mkdir ~/.vim/bundle
fi

# vim-pathoden
echo
echo "[*] Installing vim-pathogen ... "
git clone -q https://github.com/tpope/vim-pathogen $HOME/vim-pathogen
if [[ ! -d $HOME/.vim/autoload ]]; then
mkdir $HOME/.vim/autoload
fi
cp -r $HOME/vim-pathogen/autoload/* $HOME/.vim/autoload/
rm -rf $HOME/vim-pathogen
echo "    [+] Done"

# flake8 install
sudo pacman -S flake8
echo "[+] Flake8 installed!"

# vimrc
printf "\n[*] Setting up .vimrc ..."
cp $HOME/vim/.vimrc $HOME/.vimrc
echo "    [+] Done"

printf "\n[*] Setting up vim bundles..."
git clone -q https://github.com/w0rp/ale.git $HOME/.vim/bundle/ale
printf "\n\t[+] Installed: Ale from https://github.com/w0rp/ale.git\n"

git clone -q https://github.com/dracula/vim.git $HOME/.vim/bundle/dracula
printf "\n\t[+] Installed: Dracula-theme from https://github.com/dracula/dracula-theme.git\n"

git clone -q https://github.com/itchyny/lightline.vim.git $HOME/.vim/bundle/lightline
printf "\n\t[+] Installed: Light line from https://github.com/itchyny/lightline.vim.git\n"

git clone -q https://github.com/scrooloose/nerdtree.git $HOME/.vim/bundle/nerdtree
printf "\n\t[+] Installed: NERDTree from https://github.com/scrooloose/nerdtree.git\n"

git clone -q https://github.com/tpope/vim-eunuch.git $HOME/.vim/bundle/vim-eunuch
printf "\n\t[+] Installed: vim-eunuch from https://github.com/tpope/vim-eunuch.git\n"

git clone -q https://github.com/itchyny/vim-gitbranch.git $HOME/.vim/bundle/vim-gitbranch
printf "\n\t[+] Installed: vim-gitbranch from https://github.com/itchyny/vim-gitbranch.git\n"

git clone -q https://github.com/airblade/vim-gitgutter.git $HOME/.vim/bundle/vim-gitgutter
printf "\n\t[+] Installed: vim-gitgutter from https://github.com/airblade/vim-gitgutter.git\n"

printf "\n\n[+] All done.\n\n"

exit 0
